### ISSUE TITLE
Hello, i have issues with ya efi

### ISSUE THREAD

**Issue by dext2029** [AppleBreak1/EP45-UD3P-Customac#2]
So, i tried ya efi folder for installing ventura on my 1156(x3430) and it ended up with couldn't allocate class "applekeystore" or smth ant than KP

**Comment by dext2029** [comment]
Or maybe u can help me with creatin' my own efi?

**Comment by AppleBreak1** [comment]
Hi,

You have an issue with my EFI due to having a totally different hardwares.  I suggest following the [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/sandy-bridge.html#starting-point) to build your EFI.
